import type { Metadata } from "next";

import "./globals.css";
import { SteamWindow } from "react-steam-components";
import Footer from "@/components/shared/footer/footer";

export const metadata: Metadata = {
  title: "İsmail Sevgi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
